# Generated by Django 5.2.3 on 2025-06-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_remove_carrito_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
